### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by sardaukar** [CenturyLinkLabs/alpine-rails#3]
Hey, I just thought about something: the development packages are added to Alpine Linux but not needed to run the app, only to build the gems (right?). Is it possible to optimize this image by removing them after `bundle install` ?

**Comment by seanknox** [comment]
@sardaukar How much space are the development packages actually using?

**Comment by sardaukar** [comment]
Don't know - but it's easy pickings in order to slim this image even further, right?

**Comment by seanknox** [comment]
Maybe. Put up a pull request and see? :)

**Comment by sardaukar** [comment]
I've made a commit to try and optimize this (https://github.com/sardaukar/alpine-rails/commit/ccdcdc314e8f206f53604d5b619101d9738f0f2a). Is there a quick way to use this container with a Rails codebase? I'm kinda confused as the `docker images` output for my image shows 

```
slim_alpine_rails   latest              bcdc62ee3397        7 minutes ago       636.8 MB
```

Thanks for any pointers!
